secrets:
  - ak: ${ALIYUN_AK}
    sk: ${ALIYUN_SK}

resolves:
  - name: ruijc.com
    types:
      - CNAME
    value: storezhang.ruijc.com
    subdomains:
      - test
  - name: ruijc.com
    types:
      - A
    subdomains:
      - test
